"""add rebound_max_onset_minutes setting

Revision ID: 61b872a6df7a
Revises: 1b6c62c32786
Create Date: 2026-10-05 18:51:05.149629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b872a6df7a'
down_revision = '1b6c62c32786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rebound_max_onset_minutes', sa.Integer(), nullable=False, server_default=sa.text('40')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('rebound_max_onset_minutes')

    # ### end Alembic commands ###
