"""add user preferences (snooze_default, color_mode)

Revision ID: 72cee2f2896b
Revises: b6971862cdda
Create Date: 2026-07-15 14:05:13.791287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72cee2f2896b'
down_revision = 'b6971862cdda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snooze_default_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('color_mode', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('color_mode')
        batch_op.drop_column('snooze_default_minutes')

    # ### end Alembic commands ###
