"""add user preferences (snooze_default, color_mode)

Revision ID: 72cee2f2896b
Revises: b6971862cdda
Create Date: 2026-07-15 14:05:13.791287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72cee2f2896b'
down_revision = 'b6971862cdda'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snooze_default_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('color_mode', sa.String(length=10), nullable=True))
    op.execute("UPDATE users SET snooze_default_minutes = 15 WHERE snooze_default_minutes IS NULL")
    op.execute("UPDATE users SET color_mode = 'auto' WHERE color_mode IS NULL")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('snooze_default_minutes', nullable=False)
        batch_op.alter_column('color_mode', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('color_mode')
        batch_op.drop_column('snooze_default_minutes')

    # ### end Alembic commands ###
