"""add insulin stock settings

Revision ID: 852990b6a7a5
Revises: 20260824_000000
Create Date: 2026-09-25 17:57:19.835170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852990b6a7a5'
down_revision = '20260824_000000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insulin_stock', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('low_stock_days', sa.Integer(), nullable=False, server_default=sa.text('14')))
        batch_op.add_column(sa.Column('insulin_low_stock_cooldown_minutes', sa.Integer(), nullable=False, server_default=sa.text('1440')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('insulin_low_stock_cooldown_minutes')
        batch_op.drop_column('low_stock_days')
        batch_op.drop_column('insulin_stock')

    # ### end Alembic commands ###
