"""add basal stock settings

Revision ID: b18b80f7b36e
Revises: 852990b6a7a5
Create Date: 2026-09-25 19:21:05.167556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18b80f7b36e'
down_revision = '852990b6a7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basal_stock', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('basal_low_stock_cooldown_minutes', sa.Integer(), server_default='1440', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('basal_low_stock_cooldown_minutes')
        batch_op.drop_column('basal_stock')

    # ### end Alembic commands ###
