"""add webhook_token to notification_profiles

Revision ID: b6971862cdda
Revises: 20260710_170000
Create Date: 2026-07-13 14:51:13.241205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6971862cdda'
down_revision = '20260710_170000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarms_eval'))

    with op.batch_alter_table('basal_rate_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_basal_rate_history_user_changed'))

    with op.batch_alter_table('carb_factor_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carb_factor_history_user_changed'))

    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correction_factor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('streak_started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('best_streak_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('best_streak_achieved_at', sa.DateTime(timezone=True), nullable=True))
    # Fill defaults for existing rows
    op.execute("UPDATE global_settings SET correction_factor = 1.0 WHERE correction_factor IS NULL")
    op.execute("UPDATE global_settings SET best_streak_hours = 0 WHERE best_streak_hours IS NULL")
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.alter_column('correction_factor', nullable=False)
        batch_op.alter_column('best_streak_hours', nullable=False)

    with op.batch_alter_table('glucose_readings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_glucose_readings_timestamp'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_glucose_readings_timestamp'))
        batch_op.create_index(batch_op.f('ix_glucose_readings_timestamp'), ['timestamp'], unique=True)

    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_log_entries_user_created'))
        batch_op.drop_index(batch_op.f('ix_log_entries_user_type'))
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notification_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('webhook_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_notification_profiles_webhook_token'), ['webhook_token'], unique=True)

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_endpoint'))

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_active'))

    with op.batch_alter_table('twilio_call_log', schema=None) as batch_op:
        batch_op.alter_column('alarm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('twilio_call_log_alarm_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twilio_call_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('twilio_call_log_alarm_id_fkey'), 'alarms', ['alarm_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('alarm_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_active'), ['active'], unique=False)

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_endpoint'), ['endpoint'], unique=False)

    with op.batch_alter_table('notification_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_profiles_webhook_token'))
        batch_op.drop_column('webhook_token')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_log_entries_user_type'), ['user_id', 'entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_user_created'), ['user_id', 'created_at'], unique=False)
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('glucose_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glucose_readings_timestamp'))
        batch_op.create_index(batch_op.f('ix_glucose_readings_timestamp'), ['timestamp'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_glucose_readings_timestamp'), ['timestamp'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('best_streak_achieved_at')
        batch_op.drop_column('best_streak_hours')
        batch_op.drop_column('streak_started_at')
        batch_op.drop_column('correction_factor')

    with op.batch_alter_table('carb_factor_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carb_factor_history_user_changed'), ['user_id', 'changed_at'], unique=False)

    with op.batch_alter_table('basal_rate_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_basal_rate_history_user_changed'), ['user_id', 'changed_at'], unique=False)

    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarms_eval'), ['user_id', 'alarm_type', 'acknowledged_at'], unique=False)

    # ### end Alembic commands ###
