"""add smart alert settings to global_settings

Revision ID: bf107c9aa9bd
Revises: 20260727_000000
Create Date: 2026-07-28 09:23:14.961121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf107c9aa9bd'
down_revision = '20260727_000000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spike_threshold_mgdl', sa.Integer(), nullable=False, server_default=sa.text('100')))
        batch_op.add_column(sa.Column('rebound_rise_threshold_mgdl', sa.Integer(), nullable=False, server_default=sa.text('80')))
        batch_op.add_column(sa.Column('rebound_window_minutes', sa.Integer(), nullable=False, server_default=sa.text('120')))
        batch_op.add_column(sa.Column('stacking_warning_hours', sa.Float(), nullable=False, server_default=sa.text('3.0')))
        batch_op.add_column(sa.Column('dawn_start_hour_utc', sa.Integer(), nullable=False, server_default=sa.text('2')))
        batch_op.add_column(sa.Column('dawn_end_hour_utc', sa.Integer(), nullable=False, server_default=sa.text('6')))
        batch_op.add_column(sa.Column('dawn_rise_threshold_mgdl', sa.Integer(), nullable=False, server_default=sa.text('20')))
        batch_op.add_column(sa.Column('bounce_window_hours', sa.Integer(), nullable=False, server_default=sa.text('4')))
        batch_op.add_column(sa.Column('bounce_hypo_threshold', sa.Integer(), nullable=False, server_default=sa.text('70')))
        batch_op.add_column(sa.Column('bounce_hyper_threshold', sa.Integer(), nullable=False, server_default=sa.text('180')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('bounce_hyper_threshold')
        batch_op.drop_column('bounce_hypo_threshold')
        batch_op.drop_column('bounce_window_hours')
        batch_op.drop_column('dawn_rise_threshold_mgdl')
        batch_op.drop_column('dawn_end_hour_utc')
        batch_op.drop_column('dawn_start_hour_utc')
        batch_op.drop_column('stacking_warning_hours')
        batch_op.drop_column('rebound_window_minutes')
        batch_op.drop_column('rebound_rise_threshold_mgdl')
        batch_op.drop_column('spike_threshold_mgdl')

    # ### end Alembic commands ###
