"""add compression_low columns

Revision ID: cb79d170d256
Revises: 20260717_010000
Create Date: 2026-07-27 10:32:56.835974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb79d170d256'
down_revision = '20260717_010000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compression_low_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('compression_low_confidence_threshold', sa.Integer(), nullable=False, server_default=sa.text('60')))

    with op.batch_alter_table('glucose_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_compression_low', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glucose_readings', schema=None) as batch_op:
        batch_op.drop_column('is_compression_low')

    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('compression_low_confidence_threshold')
        batch_op.drop_column('compression_low_enabled')

    # ### end Alembic commands ###
