"""add smart alert cooldown and overdose settings

Revision ID: cf648bc840c6
Revises: 20260728_000000
Create Date: 2026-07-29 14:12:01.964920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf648bc840c6'
down_revision = '20260728_000000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compression_cooldown_minutes', sa.Integer(), nullable=False, server_default=sa.text('60')))
        batch_op.add_column(sa.Column('postprandial_spike_cooldown_minutes', sa.Integer(), nullable=False, server_default=sa.text('120')))
        batch_op.add_column(sa.Column('hypo_rebound_cooldown_minutes', sa.Integer(), nullable=False, server_default=sa.text('120')))
        batch_op.add_column(sa.Column('insulin_stacking_cooldown_minutes', sa.Integer(), nullable=False, server_default=sa.text('180')))
        batch_op.add_column(sa.Column('dawn_phenomenon_cooldown_minutes', sa.Integer(), nullable=False, server_default=sa.text('240')))
        batch_op.add_column(sa.Column('bounce_cycle_cooldown_minutes', sa.Integer(), nullable=False, server_default=sa.text('240')))
        batch_op.add_column(sa.Column('combined_overdose_cooldown_minutes', sa.Integer(), nullable=False, server_default=sa.text('300')))
        batch_op.add_column(sa.Column('combined_overdose_crash_window_hours', sa.Float(), nullable=False, server_default=sa.text('4.0')))
        batch_op.add_column(sa.Column('combined_overdose_crash_threshold_mgdl', sa.Integer(), nullable=False, server_default=sa.text('70')))
        batch_op.add_column(sa.Column('combined_overdose_iob_warning_threshold', sa.Float(), nullable=False, server_default=sa.text('3.0')))
        batch_op.add_column(sa.Column('combined_overdose_meal_age_hours', sa.Float(), nullable=False, server_default=sa.text('2.0')))
        batch_op.add_column(sa.Column('combined_overdose_fall_rate_mgdl_per_5min', sa.Integer(), nullable=False, server_default=sa.text('5')))
        batch_op.add_column(sa.Column('rebound_require_no_carbs', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('rebound_require_no_carbs')
        batch_op.drop_column('combined_overdose_fall_rate_mgdl_per_5min')
        batch_op.drop_column('combined_overdose_meal_age_hours')
        batch_op.drop_column('combined_overdose_iob_warning_threshold')
        batch_op.drop_column('combined_overdose_crash_threshold_mgdl')
        batch_op.drop_column('combined_overdose_crash_window_hours')
        batch_op.drop_column('combined_overdose_cooldown_minutes')
        batch_op.drop_column('bounce_cycle_cooldown_minutes')
        batch_op.drop_column('dawn_phenomenon_cooldown_minutes')
        batch_op.drop_column('insulin_stacking_cooldown_minutes')
        batch_op.drop_column('hypo_rebound_cooldown_minutes')
        batch_op.drop_column('postprandial_spike_cooldown_minutes')
        batch_op.drop_column('compression_cooldown_minutes')

    # ### end Alembic commands ###
