"""add user color preferences

Revision ID: e49ca9a43f28
Revises: 72cee2f2896b
Create Date: 2026-07-15 17:34:46.784689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49ca9a43f28'
down_revision = '72cee2f2896b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_bg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('color_primary', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('color_primary')
        batch_op.drop_column('color_bg')

    # ### end Alembic commands ###
